### ISSUE TITLE
Incorrect parsing of spaces in arguments

### ISSUE THREAD

**Issue by piegamesde** [michaellass/archlinux-java-run#2]
If I call something like `archlinux-java-run -- "arg with space"`, it will run something like `/usr/lib/jvm/java-14-openjdk/bin/java arg with space`. Note that the quotes around it disappeared, thus splitting that argument into three.

A good way to find these bugs is pasting the code on https://www.shellcheck.net/, which indeed does report a lot of issues, some potentially related to this issue.

**Comment by michaellass** [comment]
I just pushed 7b149f9af5885169413070f7844565f4a2ea6f3c which should fix this issue. Could you do me a favor and test if this works in your environment?

Basically, you can copy the script from git (https://raw.githubusercontent.com/michaellass/archlinux-java-run/master/archlinux-java-run.sh) directly to /usr/bin/archlinux-java-run. The only thing you need to adjust afterwards is that you modify line 30 (https://github.com/michaellass/archlinux-java-run/blob/master/archlinux-java-run.sh#L30) and set JAVADIR to /usr/share/java.

Shellcheck indeed shows a couple of code smells which I will go through at some point in time. However, this issue was a bit more subtle.

**Comment by piegamesde** [comment]
WFM

**Comment by piegamesde** [comment]
Please release a new version so that I can set it as minimum requirement in my project.

**Comment by michaellass** [comment]
Yeah, this somehow got forgotten right before the finish line. Expect a new release within the next 24 hours.

**Comment by michaellass** [comment]
@piegamesde I just pushed a new version to AUR.

**Comment by piegamesde** [comment]
Thank you
